camera/horizontal_fov: 115.0
camera/vertical_fov: 60.0

raycast/dr:     0.1
raycast/dphi:   10
raycast/dtheta: 10

system/bbx/r: 0.4
system/bbx/overshoot: 0.1

aep/gain/r_min: 0
aep/gain/r_max: 7
aep/gain/zero: 2
aep/gain/lambda: 0.5
aep/gain/sigma_thresh: 0.2
aep/tree/extension_range: 3.0
aep/tree/max_sampling_radius: 30
aep/tree/initial_iterations: 100
aep/tree/cutoff_iterations: 400

rrt/min_nodes: 100

# bounding box: necessary to limit the simulation 
# scenario (smaller than actual gazebo scenario)
# AEP apartment
# boundary/min: [ -10.0,  -5.0, 0.3]
# boundary/max: [ 10.0,   5.0,  2.5]
# AEP office
# boundary/min: [ -27.0,  -3.0, 0.3]
# boundary/max: [ 3.0,   17.0,  2.5]
# Garage
# boundary/min: [ -10.0,  -3.0, 0.3]
# boundary/max: [ 24.0,   30.5,  2.5]
# Office
# boundary/min: [ -2.0,  -2.0, 0.3]
# boundary/max: [ 8.0,   10.0,  2.5]
# Power plant
# boundary/min: [ -1.0,  -24.0, -4.0]
# boundary/max: [ 30.0,   7.0,  26.0]
# Triangle small
boundary/min: [ -10.0,  -3.0, 0.3]
boundary/max: [ 83.3,   90.3,  2.5]

visualize_rays: false
visualize_tree: true
visualize_exploration_area: true

robot_frame: "fcu"
world_frame: "map"

